export const PROGRAM_DAYS = [
  {
    day: 'Monday',
    label: 'Board Strength',
    type: 'hard',
    color: '#e84a2e',
    icon: '◈',
    focus: 'Body Tension & Power',
    warmup: [
      '10 min easy traversing on main wall',
      'Joint circles: wrists, elbows, shoulders',
      '5 min easy footwork drills (silent feet)',
    ],
    mainWork: [
      {
        name: 'Kilter Board Bouldering',
        detail: 'Set angle 35–45°. Pick problems V3–V5. Full rest 3–4 min between attempts.',
        sets: '8–10 problems',
        focus: 'Focus on keeping hips into the wall. If you\'re barn-dooring, you\'ve lost tension.',
      },
      {
        name: 'Tension Board Core Series',
        detail: 'After bouldering, drop to 25° angle. Do 3 problems specifically chosen for compression/roof-style body tension.',
        sets: '3 problems × 2 attempts',
        focus: 'Squeeze glutes, lock off with lower body, don\'t just pull with arms.',
      },
    ],
    drills: [
      { name: 'Hollow Body Holds', detail: '3 × 20 sec on floor. Mimic climbing tension.' },
      { name: 'Plank Rotations', detail: '3 × 10 each side. Rotational core for hip turns.' },
    ],
    cooldown: '10 min easy walking. Stretch hip flexors and forearm extensors.',
    duration: '90 min',
  },
  {
    day: 'Tuesday',
    label: 'Footwork & Technique',
    type: 'technique',
    color: '#2a9d8f',
    icon: '◉',
    focus: 'Precision & Movement',
    warmup: [
      '15 min easy climbing, focus only on feet — look at every foothold before stepping',
      '5 × traverse length, keeping feet silent (no scraping)',
    ],
    mainWork: [
      {
        name: 'Silent Feet Circuits',
        detail: 'Pick routes 1–2 grades below your max (V3–V4). Climb them with zero foot noise. If your foot scrapes, downclimb and restart.',
        sets: '6 laps total',
        focus: 'Your eyes should hit the foothold BEFORE your foot does. Develop the habit now.',
      },
      {
        name: 'Hover Hand Drill',
        detail: 'Climb easy routes but hover each hand 2 inches above holds before grabbing. Forces slower, deliberate movement and better footwork.',
        sets: '4 laps',
        focus: 'Slow down. This isn\'t about fitness — it\'s about building deliberate movement patterns.',
      },
      {
        name: 'Feet-Only Traversing',
        detail: 'Find a low traverse. Move only using your feet — hands are just for balance, not pulling. Exaggerates hip positioning.',
        sets: '5 min continuous',
        focus: 'Feel how far you can reach with your feet before needing to move hands.',
      },
    ],
    drills: [
      { name: 'Slab Climbing', detail: '20 min on slab. Nothing builds footwork trust like slab where feet are everything.' },
      { name: 'Downclimbing', detail: 'Every route climbed today, downclimb it. Forces weight over feet.' },
    ],
    cooldown: 'Hip flexor stretch 2 min each side. Ankle circles.',
    duration: '75 min',
  },
  {
    day: 'Wednesday',
    label: 'Gym Strength',
    type: 'gym',
    color: '#e9c46a',
    icon: '◇',
    focus: 'Antagonist & Core',
    warmup: [
      '10 min light cardio (row or bike)',
      'Band pull-aparts 3 × 15',
      'Shoulder dislocates with band',
    ],
    mainWork: [
      {
        name: 'Dead Hangs (Passive Tendon Load)',
        detail: 'Full crimp on 20mm edge. Hang passively — no pulling. This is tendon adaptation, not strength training. At 8 months, keep it light.',
        sets: '5 × 10 sec @ ~60–70% max effort, 2 min rest',
        focus: 'STOP if you feel any tendon pain. This is the most injury-prone exercise. Conservative is smart here.',
      },
      {
        name: 'Push-Up Variations',
        detail: 'Wide push-ups, archer push-ups, and regular. Protects shoulders and elbows by training the opposing muscles to climbing\'s pulling.',
        sets: '3 × 10 each variation',
        focus: 'Antagonist training prevents the shoulder imbalances almost every climber develops.',
      },
      {
        name: 'L-Sit Progressions',
        detail: 'On parallettes or dip bars. Tuck L-sit → one-leg extended → full L-sit. This directly trains the hip flexor + core tension pattern used in steep climbing.',
        sets: '4 × max hold (target 15–20 sec)',
        focus: 'The connection between hip flexors and core IS body tension on steep terrain.',
      },
      {
        name: 'Wrist Curls + Reverse Curls',
        detail: 'Light weight. Trains forearm extensors — the muscles climbers never train and always injure.',
        sets: '3 × 15 each direction',
        focus: 'Injury prevention. Non-negotiable.',
      },
    ],
    drills: [
      { name: 'Ring Rows', detail: '3 × 8. Retraction-focused, good scapular health.' },
      { name: 'Copenhagen Plank', detail: '3 × 20 sec each side. Hip adductor strength for flagging.' },
    ],
    cooldown: 'Full shoulder stretch series. Doorframe pec stretch.',
    duration: '60 min',
  },
  {
    day: 'Thursday',
    label: 'Hard Bouldering',
    type: 'hard',
    color: '#e84a2e',
    icon: '◈',
    focus: 'Project & Limit Climbing',
    warmup: [
      '20 min progressive climbing: V0 → V1 → V2 → V3 → V4',
      'Finger tendon warm-up: open hand crimps on large holds, 3 × 10 sec',
    ],
    mainWork: [
      {
        name: 'Project Bouldering',
        detail: 'Pick 2–3 problems at V5–V6 that specifically challenge body tension (steep, compression, or coordination moves). Spend 20–30 min on each.',
        sets: '2–3 projects, ~25 min each',
        focus: 'Break problems into sections. Identify the crux move — is it tension loss? Foot placement? Don\'t just throw yourself at it.',
      },
      {
        name: 'Tension Board Volume',
        detail: 'After projects, 20 min on the tension board at a moderate angle. Pick problems you can mostly do — this builds strength through volume.',
        sets: '6–8 moderate problems',
        focus: 'Quality of movement matters even on easier problems. No sloppy reps.',
      },
    ],
    drills: [],
    cooldown: '10 min easy climbing. Forearm massage with lacrosse ball. Hang from bar passively to decompress.',
    duration: '2 hours',
  },
  {
    day: 'Friday',
    label: 'Endurance',
    type: 'endurance',
    color: '#457b9d',
    icon: '○',
    focus: 'ARC & Pump Tolerance',
    warmup: [
      '5 min easy traversing',
      'Shoulder mobility sequence',
    ],
    mainWork: [
      {
        name: 'ARC Training (Aerobic Restoration & Capillarity)',
        detail: 'Pick routes 3–4 grades below your max (V1–V2). Climb continuously for 20–30 minutes without stopping. You should feel a mild pump but be able to hold a conversation. If you\'re getting pumped out, go easier.',
        sets: '2 × 20 min with 10 min rest between',
        focus: 'This builds the aerobic base that lets you recover mid-route. Most boulderers skip this and pay for it. It\'s boring — do it anyway.',
      },
      {
        name: '4×4s',
        detail: 'Pick 4 problems you can do easily. Climb all 4 back-to-back with 10 sec rest between problems. Rest 4 min. Repeat 4 times.',
        sets: '4 rounds',
        focus: 'Builds pump tolerance and the ability to keep moving when your forearms are screaming.',
      },
    ],
    drills: [
      { name: 'Down-climbing Every Route', detail: 'Adds volume and builds control under fatigue.' },
    ],
    cooldown: '10 min walk. Full-body stretch: hamstrings, hips, shoulders, forearms.',
    duration: '90 min',
  },
  {
    day: 'Saturday',
    label: 'Active Recovery',
    type: 'recovery',
    color: '#6a994e',
    icon: '◌',
    focus: 'Mobility & Light Movement',
    warmup: [],
    mainWork: [
      {
        name: 'Yoga or Mobility Flow',
        detail: 'Focus on hip openers (pigeon, lizard, frog), shoulder openers, and thoracic spine rotation. These directly improve your ability to use your hips on the wall.',
        sets: '30–40 min',
        focus: 'Hip mobility = better high steps, better flagging, better drop-knee. This is training.',
      },
      {
        name: 'Easy Traversing (Optional)',
        detail: 'Only if you feel good. 20 min max at V0–V1. Purely playful. No trying hard.',
        sets: 'Optional',
        focus: 'Feel the movement. No goals.',
      },
    ],
    drills: [
      { name: 'Finger Tendon Rehab', detail: 'Rice bucket or reverse wrist curls. Maintains tendon health proactively.' },
    ],
    cooldown: null,
    duration: '45 min',
  },
  {
    day: 'Sunday',
    label: 'Full Rest',
    type: 'rest',
    color: '#8ecae6',
    icon: '◯',
    focus: 'Recovery & Adaptation',
    warmup: [],
    mainWork: [
      {
        name: 'Complete Rest',
        detail: 'No climbing, no gym. Your body adapts and gets stronger during rest, not during training. This day is as important as any other.',
        sets: 'All day',
        focus: 'Sleep 8+ hours. Eat enough protein (0.7–1g per lb bodyweight). Hydrate.',
      },
    ],
    drills: [],
    cooldown: null,
    duration: '0 min training',
  },
]

export const PRINCIPLES = [
  { title: 'Tendons First', body: 'At 8 months, your tendons lag behind your muscles. Never push through finger pain. If something twinges, stop immediately.' },
  { title: 'Eyes Before Feet', body: 'Look at the foothold before your foot moves. Always. Make this a reflex in every single session.' },
  { title: 'Hips to the Wall', body: 'Most body tension failures happen at the hip. On steep terrain, actively drive your hips toward the wall rather than hanging from your arms.' },
  { title: 'Rest = Gains', body: 'Adaptation happens during rest, not training. Sleep 8+ hrs. Eat enough. Missing rest days is the fastest way to stall progress.' },
  { title: 'Deload Every 4th Week', body: 'Every 4th week, cut volume by 50%. Just climb easy and playfully. This prevents overuse injury and often unlocks new grades after.' },
]
